// Package temp
// generated by protoc-gen-boilerplate
package temp

import (
	"context"

	input "github.com/lcmaguire/protoc-gen-template/gen/temp"
	output "github.com/lcmaguire/protoc-gen-template/gen/temp"

	server "github.com/lcmaguire/protoc-gen-template/gen/temp"
)

// ExampleBidiStream implements proto.ExampleAPI.ExampleBidiStream.
func (x *ExampleAPIService) ExampleBidiStream(in server.ExampleAPI_ExampleBidiStreamServer) error {
	return nil
}
