// Package temp
// generated by protoc-gen-boilerplate
package temp

import (
	"context"

	input "github.com/lcmaguire/protoc-gen-template/gen/temp"
	output "github.com/lcmaguire/protoc-gen-template/gen/temp"

	server "github.com/lcmaguire/protoc-gen-template/gen/temp"
)

// ExampleRpc implements proto.ExampleAPI.ExampleRpc.
func (x *ExampleAPIService) ExampleRpc(ctx context.Context, in *input.Example) (*output.Example, error) {
	return nil, nil
}
