// Package temp
// generated by protoc-gen-boilerplate
package temp

import (
	"context"

	input "github.com/lcmaguire/protoc-gen-template/gen/temp"
	output "google.golang.org/protobuf/types/known/anypb"

	server "github.com/lcmaguire/protoc-gen-template/gen/temp"
)

// ExampleAnyRpc implements proto.ExampleAPI.ExampleAnyRpc.
func (x *ExampleAPIService) ExampleAnyRpc(ctx context.Context, in *input.Example) (*output.Any, error) {
	return nil, nil
}
