// Package temp
// generated by protoc-gen-boilerplate
package temp

import (
	"context"

	input "github.com/lcmaguire/protoc-gen-template/gen/temp"
	output "github.com/lcmaguire/protoc-gen-template/gen/temp"

	server "github.com/lcmaguire/protoc-gen-template/gen/temp"
)

// ExampleClientStream implements proto.ExampleAPI.ExampleClientStream.
func (x *ExampleAPIService) ExampleClientStream(in server.ExampleAPI_ExampleClientStreamServer) error {
	return nil
}
