// Package temp
// generated by protoc-gen-boilerplate
package temp

import (
	"context"

	input "github.com/lcmaguire/protoc-gen-template/gen/temp"
	output "github.com/lcmaguire/protoc-gen-template/gen/temp"

	server "github.com/lcmaguire/protoc-gen-template/gen/temp"
)

// ExampleServerStream implements proto.ExampleAPI.ExampleServerStream.
func (x *ExampleAPIService) ExampleServerStream(in *input.Example, svr server.ExampleAPI_ExampleServerStreamServer) error {
	return nil
}
