// Package temp
// generated by protoc-gen-boilerplate
package temp

import (
	temp "github.com/lcmaguire/protoc-gen-template/gen/temp"
)

// ExampleAPIService implements proto.ExampleAPI .
type ExampleAPIService struct {
	temp.UnimplementedExampleAPIServer
}
