// Package imports will import all packages so that they exist within proto registry.
// generated by protoc-gen-boilerplate
package imports

import (
	_ "google.golang.org/protobuf/types/known/anypb"
	_ "github.com/lcmaguire/protoc-gen-template/gen/temp"
)
